services:
  gateway-service:
    build:
      context: ./gateway-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      catalog-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - micro-ticket-network

  catalog-service:
    build:
      context: ./catalog-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-catalog-db:5432/${POSTGRES_CATALOG_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_CATALOG_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_CATALOG_PASSWORD}
    depends_on:
      postgres-catalog-db:
        condition: service_healthy
    networks:
      - micro-ticket-network

  order-service:
    build:
      context: ./order-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order-db:5432/${POSTGRES_ORDER_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_ORDER_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_ORDER_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      APP_CATALOG_SERVICE_BASE_URL: ${CATALOG_SERVICE_URL}
      APP_MESSAGING_EXCHANGE_NAME: ${RABBITMQ_EXCHANGE_NAME}
      APP_MESSAGING_QUEUE_NAME: ${RABBITMQ_QUEUE_NAME}
      APP_MESSAGING_BINDING_ROUTING_KEY: ${RABBITMQ_BINDING_ROUTING_KEY}
      APP_MESSAGING_ORDER_CREATED_ROUTING_KEY: ${RABBITMQ_ORDER_CREATED_ROUTING_KEY}
    depends_on:
      postgres-order-db:
        condition: service_healthy
      catalog-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - micro-ticket-network

  notification-service:
    build:
      context: ./notification-service
    restart: unless-stopped
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      APP_MESSAGING_EXCHANGE_NAME: ${RABBITMQ_EXCHANGE_NAME}
      APP_MESSAGING_QUEUE_NAME: ${RABBITMQ_QUEUE_NAME}
      APP_MESSAGING_BINDING_ROUTING_KEY: ${RABBITMQ_BINDING_ROUTING_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - micro-ticket-network

  postgres-catalog-db:
    image: postgres:17-alpine
    container_name: postgres-catalog-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_CATALOG_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CATALOG_PASSWORD}
      POSTGRES_DB: ${POSTGRES_CATALOG_DB}
    ports:
      - "${POSTGRES_CATALOG_PORT}:5432"
    volumes:
      - catalogms_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - micro-ticket-network

  postgres-order-db:
    image: postgres:17-alpine
    container_name: postgres-order-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_ORDER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ORDER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ORDER_DB}
    ports:
      - "${POSTGRES_ORDER_PORT}:5432"
    volumes:
      - orderms_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - micro-ticket-network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - micro-ticket-network

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9999:8080"
    networks:
      - micro-ticket-network

volumes:
  catalogms_postgres_data:
  orderms_postgres_data:
  rabbitmq_data:

networks:
  micro-ticket-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "m-ticket-net"