spring.application.name=order-service

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

app.catalog-service.base-url=http://catalog-service:8080

app.messaging.exchange-name=orderExchange
app.messaging.queue-name=notificationQueue
app.messaging.binding-routing-key=order.routing.#
app.messaging.order-created-routing-key=order.routing.createOrder