spring.application.name=order-service

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

app.catalog-service.base-url=http://catalog-service:8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-x76mb7fc03140zha.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api.microticket.com

app.auth0.email-claim=https://micro-ticket.app/email

app.messaging.exchange-name=orderExchange
app.messaging.queue-name=notificationQueue
app.messaging.binding-routing-key=order.routing.#
app.messaging.order-created-routing-key=order.routing.createOrder